//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from slp.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="slpParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface IslpListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="slpParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] slpParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="slpParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] slpParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="slpParser.assoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssoc([NotNull] slpParser.AssocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="slpParser.assoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssoc([NotNull] slpParser.AssocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="slpParser.opdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpdef([NotNull] slpParser.OpdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="slpParser.opdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpdef([NotNull] slpParser.OpdefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="slpParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] slpParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="slpParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] slpParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="slpParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToken([NotNull] slpParser.TokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="slpParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToken([NotNull] slpParser.TokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="slpParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] slpParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="slpParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] slpParser.BlockContext context);
}
