//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from slp.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class slpParser : Parser {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, EXPORT=33, CLASS=34, TRUE=35, FAIL=36, NULL=37, STRING=38, INT=39, 
		FLOAT=40, ID=41, NATIVE=42, COMMENT=43, LINE_COMMENT=44, OPEN_PAREN=45, 
		CLOSE_PAREN=46, OPEN_BRACK=47, CLOSE_BRACK=48, OPEN_BRACE=49, CLOSE_BRACE=50, 
		NEWLINE=51, WS=52, INDENT=53, DEDENT=54;
	public const int
		RULE_program = 0, RULE_predicate = 1, RULE_decList = 2, RULE_declaration = 3, 
		RULE_exp = 4, RULE_id = 5, RULE_nat = 6, RULE_call = 7, RULE_expList = 8, 
		RULE_rul = 9;
	public static readonly string[] ruleNames = {
		"program", "predicate", "decList", "declaration", "exp", "id", "nat", 
		"call", "expList", "rul"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "':-'", "'.'", "','", "'<'", "'>'", "'?'", "'!'", "'^'", 
		"'/'", "'*'", "'**'", "'*?'", "'*!'", "'*-'", "'-'", "'\\+-'", "'+-'", 
		"'+'", "'-+'", "'++'", "'=='", "'='", "':='", "'<='", "'>='", "'@'", "'::'", 
		"'?->'", "'-->'", "'->'", "'||'", "'export'", "'class'", "'true'", "'fail'", 
		"'<>'", null, null, null, null, null, null, null, "'('", "')'", "'['", 
		"']'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "EXPORT", "CLASS", 
		"TRUE", "FAIL", "NULL", "STRING", "INT", "FLOAT", "ID", "NATIVE", "COMMENT", 
		"LINE_COMMENT", "OPEN_PAREN", "CLOSE_PAREN", "OPEN_BRACK", "CLOSE_BRACK", 
		"OPEN_BRACE", "CLOSE_BRACE", "NEWLINE", "WS", "INDENT", "DEDENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "slp.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public slpParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgramContext : ParserRuleContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 20; exp(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PredicateContext : ParserRuleContext {
		public DecListContext inParams;
		public DecListContext outParams;
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public ITerminalNode EXPORT() { return GetToken(slpParser.EXPORT, 0); }
		public DecListContext[] decList() {
			return GetRuleContexts<DecListContext>();
		}
		public DecListContext decList(int i) {
			return GetRuleContext<DecListContext>(i);
		}
		public PredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_predicate; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterPredicate(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitPredicate(this);
		}
	}

	[RuleVersion(0)]
	public PredicateContext predicate() {
		PredicateContext _localctx = new PredicateContext(Context, State);
		EnterRule(_localctx, 2, RULE_predicate);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 23;
			_la = TokenStream.La(1);
			if (_la==EXPORT) {
				{
				State = 22; Match(EXPORT);
				}
			}

			State = 25; Match(ID);
			State = 26; Match(OPEN_PAREN);
			State = 28;
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				State = 27; _localctx.inParams = decList();
				}
				break;
			}
			State = 32;
			_la = TokenStream.La(1);
			if (_la==T__0) {
				{
				State = 30; Match(T__0);
				State = 31; _localctx.outParams = decList();
				}
			}

			State = 34; Match(CLOSE_PAREN);
			State = 35; Match(T__1);
			State = 36; exp(0);
			State = 37; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DecListContext : ParserRuleContext {
		public DeclarationContext[] declaration() {
			return GetRuleContexts<DeclarationContext>();
		}
		public DeclarationContext declaration(int i) {
			return GetRuleContext<DeclarationContext>(i);
		}
		public DecListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_decList; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterDecList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitDecList(this);
		}
	}

	[RuleVersion(0)]
	public DecListContext decList() {
		DecListContext _localctx = new DecListContext(Context, State);
		EnterRule(_localctx, 4, RULE_decList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 39; declaration();
			State = 44;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==T__3) {
				{
				{
				State = 40; Match(T__3);
				State = 41; declaration();
				}
				}
				State = 46;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclarationContext : ParserRuleContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public DeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitDeclaration(this);
		}
	}

	[RuleVersion(0)]
	public DeclarationContext declaration() {
		DeclarationContext _localctx = new DeclarationContext(Context, State);
		EnterRule(_localctx, 6, RULE_declaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47; exp(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpContext : ParserRuleContext {
		public ExpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exp; } }
	 
		public ExpContext() { }
		public virtual void CopyFrom(ExpContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class SwitchContext : ExpContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public SwitchContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterSwitch(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitSwitch(this);
		}
	}
	public partial class SugarContext : ExpContext {
		public ExpContext[] exp() {
			return GetRuleContexts<ExpContext>();
		}
		public ExpContext exp(int i) {
			return GetRuleContext<ExpContext>(i);
		}
		public SugarContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterSugar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitSugar(this);
		}
	}
	public partial class AssociativeContext : ExpContext {
		public ExpContext[] exp() {
			return GetRuleContexts<ExpContext>();
		}
		public ExpContext exp(int i) {
			return GetRuleContext<ExpContext>(i);
		}
		public AssociativeContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterAssociative(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitAssociative(this);
		}
	}
	public partial class MemberContext : ExpContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public MemberContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterMember(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitMember(this);
		}
	}
	public partial class BinaryContext : ExpContext {
		public ExpContext[] exp() {
			return GetRuleContexts<ExpContext>();
		}
		public ExpContext exp(int i) {
			return GetRuleContext<ExpContext>(i);
		}
		public BinaryContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterBinary(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitBinary(this);
		}
	}
	public partial class OpVarContext : ExpContext {
		public ExpContext[] exp() {
			return GetRuleContexts<ExpContext>();
		}
		public ExpContext exp(int i) {
			return GetRuleContext<ExpContext>(i);
		}
		public OpVarContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterOpVar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitOpVar(this);
		}
	}
	public partial class OperatorContext : ExpContext {
		public OperatorContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterOperator(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitOperator(this);
		}
	}
	public partial class OpVarUnaryContext : ExpContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public OpVarUnaryContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterOpVarUnary(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitOpVarUnary(this);
		}
	}
	public partial class ParaContext : ExpContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public ParaContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterPara(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitPara(this);
		}
	}
	public partial class NotContext : ExpContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public NotContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterNot(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitNot(this);
		}
	}
	public partial class SingContext : ExpContext {
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public CallContext call() {
			return GetRuleContext<CallContext>(0);
		}
		public NatContext nat() {
			return GetRuleContext<NatContext>(0);
		}
		public ITerminalNode INT() { return GetToken(slpParser.INT, 0); }
		public ITerminalNode FLOAT() { return GetToken(slpParser.FLOAT, 0); }
		public ITerminalNode STRING() { return GetToken(slpParser.STRING, 0); }
		public ITerminalNode TRUE() { return GetToken(slpParser.TRUE, 0); }
		public ITerminalNode FAIL() { return GetToken(slpParser.FAIL, 0); }
		public ITerminalNode NULL() { return GetToken(slpParser.NULL, 0); }
		public SingContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterSing(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitSing(this);
		}
	}
	public partial class QuestionContext : ExpContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public QuestionContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterQuestion(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitQuestion(this);
		}
	}
	public partial class AttributeContext : ExpContext {
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public NatContext nat() {
			return GetRuleContext<NatContext>(0);
		}
		public CallContext[] call() {
			return GetRuleContexts<CallContext>();
		}
		public CallContext call(int i) {
			return GetRuleContext<CallContext>(i);
		}
		public AttributeContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterAttribute(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitAttribute(this);
		}
	}
	public partial class MinContext : ExpContext {
		public ExpContext exp() {
			return GetRuleContext<ExpContext>(0);
		}
		public MinContext(ExpContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterMin(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitMin(this);
		}
	}

	[RuleVersion(0)]
	public ExpContext exp() {
		return exp(0);
	}

	private ExpContext exp(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpContext _localctx = new ExpContext(Context, _parentState);
		ExpContext _prevctx = _localctx;
		int _startState = 8;
		EnterRecursionRule(_localctx, 8, RULE_exp, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				{
				_localctx = new NotContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 50; Match(T__7);
				State = 51; exp(38);
				}
				break;
			case 2:
				{
				_localctx = new MinContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 52; Match(T__15);
				State = 53; exp(30);
				}
				break;
			case 3:
				{
				_localctx = new MinContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 54; Match(T__16);
				State = 55; exp(29);
				}
				break;
			case 4:
				{
				_localctx = new OpVarUnaryContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 56; Match(T__17);
				State = 57; exp(28);
				}
				break;
			case 5:
				{
				_localctx = new SugarContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 58; Match(T__28);
				State = 59; exp(11);
				}
				break;
			case 6:
				{
				_localctx = new SugarContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 60; Match(T__29);
				State = 61; exp(10);
				}
				break;
			case 7:
				{
				_localctx = new SugarContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 62; Match(T__30);
				State = 63; exp(9);
				}
				break;
			case 8:
				{
				_localctx = new ParaContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 64; Match(T__0);
				State = 65; exp(2);
				}
				break;
			case 9:
				{
				_localctx = new AttributeContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				do {
					{
					{
					State = 66; Match(T__4);
					State = 67; call();
					State = 68; Match(T__5);
					}
					}
					State = 72;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				} while ( _la==T__4 );
				State = 76;
				switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
				case 1:
					{
					State = 74; id();
					}
					break;
				case 2:
					{
					State = 75; nat();
					}
					break;
				}
				}
				break;
			case 10:
				{
				_localctx = new SingContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 82;
				switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
				case 1:
					{
					State = 78; id();
					}
					break;
				case 2:
					{
					State = 79; call();
					}
					break;
				case 3:
					{
					State = 80; nat();
					}
					break;
				case 4:
					{
					State = 81;
					_la = TokenStream.La(1);
					if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TRUE) | (1L << FAIL) | (1L << NULL) | (1L << STRING) | (1L << INT) | (1L << FLOAT))) != 0)) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
					    Consume();
					}
					}
					break;
				}
				}
				break;
			case 11:
				{
				_localctx = new ParaContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 84; Match(OPEN_PAREN);
				State = 85; exp(0);
				State = 86; Match(CLOSE_PAREN);
				}
				break;
			case 12:
				{
				_localctx = new OperatorContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 100;
				switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
				case 1:
					{
					State = 88; Match(OPEN_PAREN);
					State = 89; Match(T__18);
					State = 90; Match(CLOSE_PAREN);
					}
					break;
				case 2:
					{
					State = 91; Match(OPEN_PAREN);
					State = 92; Match(T__15);
					State = 93; Match(CLOSE_PAREN);
					}
					break;
				case 3:
					{
					State = 94; Match(OPEN_PAREN);
					State = 95; Match(T__10);
					State = 96; Match(CLOSE_PAREN);
					}
					break;
				case 4:
					{
					State = 97; Match(OPEN_PAREN);
					State = 98; Match(T__9);
					State = 99; Match(CLOSE_PAREN);
					}
					break;
				}
				}
				break;
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 197;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 195;
					switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
					case 1:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 104;
						if (!(Precpred(Context, 37))) throw new FailedPredicateException(this, "Precpred(Context, 37)");
						State = 105; Match(T__8);
						State = 106; exp(38);
						}
						break;
					case 2:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 107;
						if (!(Precpred(Context, 36))) throw new FailedPredicateException(this, "Precpred(Context, 36)");
						State = 108; Match(T__9);
						State = 109; exp(37);
						}
						break;
					case 3:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 110;
						if (!(Precpred(Context, 35))) throw new FailedPredicateException(this, "Precpred(Context, 35)");
						State = 111; Match(T__10);
						State = 112; exp(36);
						}
						break;
					case 4:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 113;
						if (!(Precpred(Context, 34))) throw new FailedPredicateException(this, "Precpred(Context, 34)");
						State = 114; Match(T__11);
						State = 115; exp(35);
						}
						break;
					case 5:
						{
						_localctx = new SugarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 116;
						if (!(Precpred(Context, 33))) throw new FailedPredicateException(this, "Precpred(Context, 33)");
						State = 117; Match(T__12);
						State = 118; exp(34);
						}
						break;
					case 6:
						{
						_localctx = new SugarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 119;
						if (!(Precpred(Context, 32))) throw new FailedPredicateException(this, "Precpred(Context, 32)");
						State = 120; Match(T__13);
						State = 121; exp(33);
						}
						break;
					case 7:
						{
						_localctx = new SugarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 122;
						if (!(Precpred(Context, 31))) throw new FailedPredicateException(this, "Precpred(Context, 31)");
						State = 123; Match(T__14);
						State = 124; exp(32);
						}
						break;
					case 8:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 125;
						if (!(Precpred(Context, 27))) throw new FailedPredicateException(this, "Precpred(Context, 27)");
						State = 126; Match(T__15);
						State = 127; exp(28);
						}
						break;
					case 9:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 128;
						if (!(Precpred(Context, 26))) throw new FailedPredicateException(this, "Precpred(Context, 26)");
						State = 129; Match(T__18);
						State = 130; exp(27);
						}
						break;
					case 10:
						{
						_localctx = new OpVarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 131;
						if (!(Precpred(Context, 25))) throw new FailedPredicateException(this, "Precpred(Context, 25)");
						State = 132; Match(T__17);
						State = 133; exp(26);
						}
						break;
					case 11:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 134;
						if (!(Precpred(Context, 24))) throw new FailedPredicateException(this, "Precpred(Context, 24)");
						State = 135; Match(T__16);
						State = 136; exp(25);
						}
						break;
					case 12:
						{
						_localctx = new OpVarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 137;
						if (!(Precpred(Context, 23))) throw new FailedPredicateException(this, "Precpred(Context, 23)");
						State = 138; Match(T__19);
						State = 139; exp(24);
						}
						break;
					case 13:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 140;
						if (!(Precpred(Context, 22))) throw new FailedPredicateException(this, "Precpred(Context, 22)");
						State = 141; Match(T__20);
						State = 142; exp(23);
						}
						break;
					case 14:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 143;
						if (!(Precpred(Context, 21))) throw new FailedPredicateException(this, "Precpred(Context, 21)");
						State = 144; Match(T__21);
						State = 145; exp(22);
						}
						break;
					case 15:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 146;
						if (!(Precpred(Context, 20))) throw new FailedPredicateException(this, "Precpred(Context, 20)");
						State = 147; Match(T__22);
						State = 148; exp(21);
						}
						break;
					case 16:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 149;
						if (!(Precpred(Context, 19))) throw new FailedPredicateException(this, "Precpred(Context, 19)");
						State = 150; Match(T__23);
						State = 151; exp(20);
						}
						break;
					case 17:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 152;
						if (!(Precpred(Context, 18))) throw new FailedPredicateException(this, "Precpred(Context, 18)");
						State = 153; Match(T__4);
						State = 154; exp(19);
						}
						break;
					case 18:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 155;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 156; Match(T__5);
						State = 157; exp(18);
						}
						break;
					case 19:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 158;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 159; Match(T__24);
						State = 160; exp(17);
						}
						break;
					case 20:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 161;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 162; Match(T__25);
						State = 163; exp(16);
						}
						break;
					case 21:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 164;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 165; Match(T__3);
						State = 166; exp(14);
						}
						break;
					case 22:
						{
						_localctx = new BinaryContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 167;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 168; Match(T__27);
						State = 169; exp(13);
						}
						break;
					case 23:
						{
						_localctx = new SugarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 170;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 171; Match(T__28);
						State = 172; exp(9);
						}
						break;
					case 24:
						{
						_localctx = new SugarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 173;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 174; Match(T__29);
						State = 175; exp(8);
						}
						break;
					case 25:
						{
						_localctx = new SugarContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 176;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 177; Match(T__30);
						State = 178; exp(7);
						}
						break;
					case 26:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 179;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 180; Match(T__0);
						State = 181; exp(6);
						}
						break;
					case 27:
						{
						_localctx = new AssociativeContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 182;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 183; Match(T__31);
						State = 184; exp(5);
						}
						break;
					case 28:
						{
						_localctx = new MemberContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 185;
						if (!(Precpred(Context, 40))) throw new FailedPredicateException(this, "Precpred(Context, 40)");
						State = 186; Match(T__2);
						State = 187; Match(ID);
						}
						break;
					case 29:
						{
						_localctx = new QuestionContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 188;
						if (!(Precpred(Context, 39))) throw new FailedPredicateException(this, "Precpred(Context, 39)");
						State = 189; Match(T__6);
						}
						break;
					case 30:
						{
						_localctx = new SwitchContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 190;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 191; Match(T__26);
						State = 192; id();
						}
						break;
					case 31:
						{
						_localctx = new ParaContext(new ExpContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_exp);
						State = 193;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 194; Match(T__3);
						}
						break;
					}
					} 
				}
				State = 199;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class IdContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public IdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterId(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitId(this);
		}
	}

	[RuleVersion(0)]
	public IdContext id() {
		IdContext _localctx = new IdContext(Context, State);
		EnterRule(_localctx, 10, RULE_id);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200; Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NatContext : ParserRuleContext {
		public ITerminalNode NATIVE() { return GetToken(slpParser.NATIVE, 0); }
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public NatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nat; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterNat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitNat(this);
		}
	}

	[RuleVersion(0)]
	public NatContext nat() {
		NatContext _localctx = new NatContext(Context, State);
		EnterRule(_localctx, 12, RULE_nat);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203;
			_la = TokenStream.La(1);
			if (_la==ID) {
				{
				State = 202; Match(ID);
				}
			}

			State = 205; Match(NATIVE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CallContext : ParserRuleContext {
		public CallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call; } }
	 
		public CallContext() { }
		public virtual void CopyFrom(CallContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DelayedCall1Context : CallContext {
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public CallContext[] call() {
			return GetRuleContexts<CallContext>();
		}
		public CallContext call(int i) {
			return GetRuleContext<CallContext>(i);
		}
		public ExpListContext expList() {
			return GetRuleContext<ExpListContext>(0);
		}
		public DelayedCall1Context(CallContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterDelayedCall1(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitDelayedCall1(this);
		}
	}
	public partial class DelayedCall2Context : CallContext {
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public CallContext[] call() {
			return GetRuleContexts<CallContext>();
		}
		public CallContext call(int i) {
			return GetRuleContext<CallContext>(i);
		}
		public ExpListContext expList() {
			return GetRuleContext<ExpListContext>(0);
		}
		public DelayedCall2Context(CallContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterDelayedCall2(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitDelayedCall2(this);
		}
	}
	public partial class DeclareCallContext : CallContext {
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public CallContext[] call() {
			return GetRuleContexts<CallContext>();
		}
		public CallContext call(int i) {
			return GetRuleContext<CallContext>(i);
		}
		public ExpListContext expList() {
			return GetRuleContext<ExpListContext>(0);
		}
		public DeclareCallContext(CallContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterDeclareCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitDeclareCall(this);
		}
	}
	public partial class NormalCallContext : CallContext {
		public ITerminalNode ID() { return GetToken(slpParser.ID, 0); }
		public CallContext[] call() {
			return GetRuleContexts<CallContext>();
		}
		public CallContext call(int i) {
			return GetRuleContext<CallContext>(i);
		}
		public ExpListContext expList() {
			return GetRuleContext<ExpListContext>(0);
		}
		public NormalCallContext(CallContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterNormalCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitNormalCall(this);
		}
	}

	[RuleVersion(0)]
	public CallContext call() {
		CallContext _localctx = new CallContext(Context, State);
		EnterRule(_localctx, 14, RULE_call);
		int _la;
		try {
			State = 288;
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				_localctx = new NormalCallContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 213;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==T__4) {
					{
					{
					State = 207; Match(T__4);
					State = 208; call();
					State = 209; Match(T__5);
					}
					}
					State = 215;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 216; Match(ID);
				State = 222;
				switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
				case 1:
					{
					State = 217; Match(OPEN_PAREN);
					State = 219;
					_la = TokenStream.La(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__4) | (1L << T__7) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__28) | (1L << T__29) | (1L << T__30) | (1L << TRUE) | (1L << FAIL) | (1L << NULL) | (1L << STRING) | (1L << INT) | (1L << FLOAT) | (1L << ID) | (1L << NATIVE) | (1L << OPEN_PAREN))) != 0)) {
						{
						State = 218; expList();
						}
					}

					State = 221; Match(CLOSE_PAREN);
					}
					break;
				}
				}
				break;
			case 2:
				_localctx = new DeclareCallContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 230;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==T__4) {
					{
					{
					State = 224; Match(T__4);
					State = 225; call();
					State = 226; Match(T__5);
					}
					}
					State = 232;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 233; Match(ID);
				State = 234; Match(T__7);
				State = 240;
				switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
				case 1:
					{
					State = 235; Match(OPEN_PAREN);
					State = 237;
					_la = TokenStream.La(1);
					if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__4) | (1L << T__7) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__28) | (1L << T__29) | (1L << T__30) | (1L << TRUE) | (1L << FAIL) | (1L << NULL) | (1L << STRING) | (1L << INT) | (1L << FLOAT) | (1L << ID) | (1L << NATIVE) | (1L << OPEN_PAREN))) != 0)) {
						{
						State = 236; expList();
						}
					}

					State = 239; Match(CLOSE_PAREN);
					}
					break;
				}
				}
				break;
			case 3:
				_localctx = new DelayedCall1Context(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 248;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==T__4) {
					{
					{
					State = 242; Match(T__4);
					State = 243; call();
					State = 244; Match(T__5);
					}
					}
					State = 250;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 251; Match(ID);
				State = 252; Match(OPEN_BRACK);
				State = 254;
				_la = TokenStream.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__4) | (1L << T__7) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__28) | (1L << T__29) | (1L << T__30) | (1L << TRUE) | (1L << FAIL) | (1L << NULL) | (1L << STRING) | (1L << INT) | (1L << FLOAT) | (1L << ID) | (1L << NATIVE) | (1L << OPEN_PAREN))) != 0)) {
					{
					State = 253; expList();
					}
				}

				State = 256; Match(CLOSE_BRACK);
				}
				break;
			case 4:
				_localctx = new DelayedCall2Context(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 263;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==T__4) {
					{
					{
					State = 257; Match(T__4);
					State = 258; call();
					State = 259; Match(T__5);
					}
					}
					State = 265;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 266; Match(ID);
				State = 267; Match(T__6);
				State = 268; Match(OPEN_PAREN);
				State = 270;
				_la = TokenStream.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__4) | (1L << T__7) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__28) | (1L << T__29) | (1L << T__30) | (1L << TRUE) | (1L << FAIL) | (1L << NULL) | (1L << STRING) | (1L << INT) | (1L << FLOAT) | (1L << ID) | (1L << NATIVE) | (1L << OPEN_PAREN))) != 0)) {
					{
					State = 269; expList();
					}
				}

				State = 272; Match(CLOSE_PAREN);
				}
				break;
			case 5:
				_localctx = new DelayedCall2Context(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 279;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
				while (_la==T__4) {
					{
					{
					State = 273; Match(T__4);
					State = 274; call();
					State = 275; Match(T__5);
					}
					}
					State = 281;
					ErrorHandler.Sync(this);
					_la = TokenStream.La(1);
				}
				State = 282; Match(ID);
				State = 283; Match(T__4);
				State = 285;
				_la = TokenStream.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__4) | (1L << T__7) | (1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__28) | (1L << T__29) | (1L << T__30) | (1L << TRUE) | (1L << FAIL) | (1L << NULL) | (1L << STRING) | (1L << INT) | (1L << FLOAT) | (1L << ID) | (1L << NATIVE) | (1L << OPEN_PAREN))) != 0)) {
					{
					State = 284; expList();
					}
				}

				State = 287; Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpListContext : ParserRuleContext {
		public ExpContext[] exp() {
			return GetRuleContexts<ExpContext>();
		}
		public ExpContext exp(int i) {
			return GetRuleContext<ExpContext>(i);
		}
		public ExpListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expList; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterExpList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitExpList(this);
		}
	}

	[RuleVersion(0)]
	public ExpListContext expList() {
		ExpListContext _localctx = new ExpListContext(Context, State);
		EnterRule(_localctx, 16, RULE_expList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 290; exp(0);
			State = 295;
			ErrorHandler.Sync(this);
			_la = TokenStream.La(1);
			while (_la==T__3) {
				{
				{
				State = 291; Match(T__3);
				State = 292; exp(0);
				}
				}
				State = 297;
				ErrorHandler.Sync(this);
				_la = TokenStream.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RulContext : ParserRuleContext {
		public ExpContext[] exp() {
			return GetRuleContexts<ExpContext>();
		}
		public ExpContext exp(int i) {
			return GetRuleContext<ExpContext>(i);
		}
		public RulContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rul; } }
		public override void EnterRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.EnterRul(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IslpListener typedListener = listener as IslpListener;
			if (typedListener != null) typedListener.ExitRul(this);
		}
	}

	[RuleVersion(0)]
	public RulContext rul() {
		RulContext _localctx = new RulContext(Context, State);
		EnterRule(_localctx, 18, RULE_rul);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 299;
			_la = TokenStream.La(1);
			if (_la==EXPORT) {
				{
				State = 298; Match(EXPORT);
				}
			}

			State = 301; exp(0);
			State = 302; Match(T__23);
			State = 303; exp(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 4: return exp_sempred((ExpContext)_localctx, predIndex);
		}
		return true;
	}
	private bool exp_sempred(ExpContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 37);
		case 1: return Precpred(Context, 36);
		case 2: return Precpred(Context, 35);
		case 3: return Precpred(Context, 34);
		case 4: return Precpred(Context, 33);
		case 5: return Precpred(Context, 32);
		case 6: return Precpred(Context, 31);
		case 7: return Precpred(Context, 27);
		case 8: return Precpred(Context, 26);
		case 9: return Precpred(Context, 25);
		case 10: return Precpred(Context, 24);
		case 11: return Precpred(Context, 23);
		case 12: return Precpred(Context, 22);
		case 13: return Precpred(Context, 21);
		case 14: return Precpred(Context, 20);
		case 15: return Precpred(Context, 19);
		case 16: return Precpred(Context, 18);
		case 17: return Precpred(Context, 17);
		case 18: return Precpred(Context, 16);
		case 19: return Precpred(Context, 15);
		case 20: return Precpred(Context, 13);
		case 21: return Precpred(Context, 12);
		case 22: return Precpred(Context, 8);
		case 23: return Precpred(Context, 7);
		case 24: return Precpred(Context, 6);
		case 25: return Precpred(Context, 5);
		case 26: return Precpred(Context, 4);
		case 27: return Precpred(Context, 40);
		case 28: return Precpred(Context, 39);
		case 29: return Precpred(Context, 14);
		case 30: return Precpred(Context, 3);
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\x38\x134\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x4\v\t\v\x3\x2\x3\x2\x3\x3\x5\x3\x1A\n\x3\x3\x3\x3\x3\x3"+
		"\x3\x5\x3\x1F\n\x3\x3\x3\x3\x3\x5\x3#\n\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3"+
		"\x3\x3\x4\x3\x4\x3\x4\a\x4-\n\x4\f\x4\xE\x4\x30\v\x4\x3\x5\x3\x5\x3\x6"+
		"\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3"+
		"\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x6\x6I\n\x6\r\x6\xE"+
		"\x6J\x3\x6\x3\x6\x5\x6O\n\x6\x3\x6\x3\x6\x3\x6\x3\x6\x5\x6U\n\x6\x3\x6"+
		"\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3"+
		"\x6\x3\x6\x3\x6\x3\x6\x5\x6g\n\x6\x5\x6i\n\x6\x3\x6\x3\x6\x3\x6\x3\x6"+
		"\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3"+
		"\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6"+
		"\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3"+
		"\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6"+
		"\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3"+
		"\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6"+
		"\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3"+
		"\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\a\x6\xC6\n\x6\f\x6\xE\x6\xC9\v"+
		"\x6\x3\a\x3\a\x3\b\x5\b\xCE\n\b\x3\b\x3\b\x3\t\x3\t\x3\t\x3\t\a\t\xD6"+
		"\n\t\f\t\xE\t\xD9\v\t\x3\t\x3\t\x3\t\x5\t\xDE\n\t\x3\t\x5\t\xE1\n\t\x3"+
		"\t\x3\t\x3\t\x3\t\a\t\xE7\n\t\f\t\xE\t\xEA\v\t\x3\t\x3\t\x3\t\x3\t\x5"+
		"\t\xF0\n\t\x3\t\x5\t\xF3\n\t\x3\t\x3\t\x3\t\x3\t\a\t\xF9\n\t\f\t\xE\t"+
		"\xFC\v\t\x3\t\x3\t\x3\t\x5\t\x101\n\t\x3\t\x3\t\x3\t\x3\t\x3\t\a\t\x108"+
		"\n\t\f\t\xE\t\x10B\v\t\x3\t\x3\t\x3\t\x3\t\x5\t\x111\n\t\x3\t\x3\t\x3"+
		"\t\x3\t\x3\t\a\t\x118\n\t\f\t\xE\t\x11B\v\t\x3\t\x3\t\x3\t\x5\t\x120\n"+
		"\t\x3\t\x5\t\x123\n\t\x3\n\x3\n\x3\n\a\n\x128\n\n\f\n\xE\n\x12B\v\n\x3"+
		"\v\x5\v\x12E\n\v\x3\v\x3\v\x3\v\x3\v\x3\v\x2\x3\n\f\x2\x4\x6\b\n\f\xE"+
		"\x10\x12\x14\x2\x3\x3\x2%*\x172\x2\x16\x3\x2\x2\x2\x4\x19\x3\x2\x2\x2"+
		"\x6)\x3\x2\x2\x2\b\x31\x3\x2\x2\x2\nh\x3\x2\x2\x2\f\xCA\x3\x2\x2\x2\xE"+
		"\xCD\x3\x2\x2\x2\x10\x122\x3\x2\x2\x2\x12\x124\x3\x2\x2\x2\x14\x12D\x3"+
		"\x2\x2\x2\x16\x17\x5\n\x6\x2\x17\x3\x3\x2\x2\x2\x18\x1A\a#\x2\x2\x19\x18"+
		"\x3\x2\x2\x2\x19\x1A\x3\x2\x2\x2\x1A\x1B\x3\x2\x2\x2\x1B\x1C\a+\x2\x2"+
		"\x1C\x1E\a/\x2\x2\x1D\x1F\x5\x6\x4\x2\x1E\x1D\x3\x2\x2\x2\x1E\x1F\x3\x2"+
		"\x2\x2\x1F\"\x3\x2\x2\x2 !\a\x3\x2\x2!#\x5\x6\x4\x2\" \x3\x2\x2\x2\"#"+
		"\x3\x2\x2\x2#$\x3\x2\x2\x2$%\a\x30\x2\x2%&\a\x4\x2\x2&\'\x5\n\x6\x2\'"+
		"(\a\x5\x2\x2(\x5\x3\x2\x2\x2).\x5\b\x5\x2*+\a\x6\x2\x2+-\x5\b\x5\x2,*"+
		"\x3\x2\x2\x2-\x30\x3\x2\x2\x2.,\x3\x2\x2\x2./\x3\x2\x2\x2/\a\x3\x2\x2"+
		"\x2\x30.\x3\x2\x2\x2\x31\x32\x5\n\x6\x2\x32\t\x3\x2\x2\x2\x33\x34\b\x6"+
		"\x1\x2\x34\x35\a\n\x2\x2\x35i\x5\n\x6(\x36\x37\a\x12\x2\x2\x37i\x5\n\x6"+
		" \x38\x39\a\x13\x2\x2\x39i\x5\n\x6\x1F:;\a\x14\x2\x2;i\x5\n\x6\x1E<=\a"+
		"\x1F\x2\x2=i\x5\n\x6\r>?\a \x2\x2?i\x5\n\x6\f@\x41\a!\x2\x2\x41i\x5\n"+
		"\x6\v\x42\x43\a\x3\x2\x2\x43i\x5\n\x6\x4\x44\x45\a\a\x2\x2\x45\x46\x5"+
		"\x10\t\x2\x46G\a\b\x2\x2GI\x3\x2\x2\x2H\x44\x3\x2\x2\x2IJ\x3\x2\x2\x2"+
		"JH\x3\x2\x2\x2JK\x3\x2\x2\x2KN\x3\x2\x2\x2LO\x5\f\a\x2MO\x5\xE\b\x2NL"+
		"\x3\x2\x2\x2NM\x3\x2\x2\x2Oi\x3\x2\x2\x2PU\x5\f\a\x2QU\x5\x10\t\x2RU\x5"+
		"\xE\b\x2SU\t\x2\x2\x2TP\x3\x2\x2\x2TQ\x3\x2\x2\x2TR\x3\x2\x2\x2TS\x3\x2"+
		"\x2\x2Ui\x3\x2\x2\x2VW\a/\x2\x2WX\x5\n\x6\x2XY\a\x30\x2\x2Yi\x3\x2\x2"+
		"\x2Z[\a/\x2\x2[\\\a\x15\x2\x2\\g\a\x30\x2\x2]^\a/\x2\x2^_\a\x12\x2\x2"+
		"_g\a\x30\x2\x2`\x61\a/\x2\x2\x61\x62\a\r\x2\x2\x62g\a\x30\x2\x2\x63\x64"+
		"\a/\x2\x2\x64\x65\a\f\x2\x2\x65g\a\x30\x2\x2\x66Z\x3\x2\x2\x2\x66]\x3"+
		"\x2\x2\x2\x66`\x3\x2\x2\x2\x66\x63\x3\x2\x2\x2gi\x3\x2\x2\x2h\x33\x3\x2"+
		"\x2\x2h\x36\x3\x2\x2\x2h\x38\x3\x2\x2\x2h:\x3\x2\x2\x2h<\x3\x2\x2\x2h"+
		">\x3\x2\x2\x2h@\x3\x2\x2\x2h\x42\x3\x2\x2\x2hH\x3\x2\x2\x2hT\x3\x2\x2"+
		"\x2hV\x3\x2\x2\x2h\x66\x3\x2\x2\x2i\xC7\x3\x2\x2\x2jk\f\'\x2\x2kl\a\v"+
		"\x2\x2l\xC6\x5\n\x6(mn\f&\x2\x2no\a\f\x2\x2o\xC6\x5\n\x6\'pq\f%\x2\x2"+
		"qr\a\r\x2\x2r\xC6\x5\n\x6&st\f$\x2\x2tu\a\xE\x2\x2u\xC6\x5\n\x6%vw\f#"+
		"\x2\x2wx\a\xF\x2\x2x\xC6\x5\n\x6$yz\f\"\x2\x2z{\a\x10\x2\x2{\xC6\x5\n"+
		"\x6#|}\f!\x2\x2}~\a\x11\x2\x2~\xC6\x5\n\x6\"\x7F\x80\f\x1D\x2\x2\x80\x81"+
		"\a\x12\x2\x2\x81\xC6\x5\n\x6\x1E\x82\x83\f\x1C\x2\x2\x83\x84\a\x15\x2"+
		"\x2\x84\xC6\x5\n\x6\x1D\x85\x86\f\x1B\x2\x2\x86\x87\a\x14\x2\x2\x87\xC6"+
		"\x5\n\x6\x1C\x88\x89\f\x1A\x2\x2\x89\x8A\a\x13\x2\x2\x8A\xC6\x5\n\x6\x1B"+
		"\x8B\x8C\f\x19\x2\x2\x8C\x8D\a\x16\x2\x2\x8D\xC6\x5\n\x6\x1A\x8E\x8F\f"+
		"\x18\x2\x2\x8F\x90\a\x17\x2\x2\x90\xC6\x5\n\x6\x19\x91\x92\f\x17\x2\x2"+
		"\x92\x93\a\x18\x2\x2\x93\xC6\x5\n\x6\x18\x94\x95\f\x16\x2\x2\x95\x96\a"+
		"\x19\x2\x2\x96\xC6\x5\n\x6\x17\x97\x98\f\x15\x2\x2\x98\x99\a\x1A\x2\x2"+
		"\x99\xC6\x5\n\x6\x16\x9A\x9B\f\x14\x2\x2\x9B\x9C\a\a\x2\x2\x9C\xC6\x5"+
		"\n\x6\x15\x9D\x9E\f\x13\x2\x2\x9E\x9F\a\b\x2\x2\x9F\xC6\x5\n\x6\x14\xA0"+
		"\xA1\f\x12\x2\x2\xA1\xA2\a\x1B\x2\x2\xA2\xC6\x5\n\x6\x13\xA3\xA4\f\x11"+
		"\x2\x2\xA4\xA5\a\x1C\x2\x2\xA5\xC6\x5\n\x6\x12\xA6\xA7\f\xF\x2\x2\xA7"+
		"\xA8\a\x6\x2\x2\xA8\xC6\x5\n\x6\x10\xA9\xAA\f\xE\x2\x2\xAA\xAB\a\x1E\x2"+
		"\x2\xAB\xC6\x5\n\x6\xF\xAC\xAD\f\n\x2\x2\xAD\xAE\a\x1F\x2\x2\xAE\xC6\x5"+
		"\n\x6\v\xAF\xB0\f\t\x2\x2\xB0\xB1\a \x2\x2\xB1\xC6\x5\n\x6\n\xB2\xB3\f"+
		"\b\x2\x2\xB3\xB4\a!\x2\x2\xB4\xC6\x5\n\x6\t\xB5\xB6\f\a\x2\x2\xB6\xB7"+
		"\a\x3\x2\x2\xB7\xC6\x5\n\x6\b\xB8\xB9\f\x6\x2\x2\xB9\xBA\a\"\x2\x2\xBA"+
		"\xC6\x5\n\x6\a\xBB\xBC\f*\x2\x2\xBC\xBD\a\x5\x2\x2\xBD\xC6\a+\x2\x2\xBE"+
		"\xBF\f)\x2\x2\xBF\xC6\a\t\x2\x2\xC0\xC1\f\x10\x2\x2\xC1\xC2\a\x1D\x2\x2"+
		"\xC2\xC6\x5\f\a\x2\xC3\xC4\f\x5\x2\x2\xC4\xC6\a\x6\x2\x2\xC5j\x3\x2\x2"+
		"\x2\xC5m\x3\x2\x2\x2\xC5p\x3\x2\x2\x2\xC5s\x3\x2\x2\x2\xC5v\x3\x2\x2\x2"+
		"\xC5y\x3\x2\x2\x2\xC5|\x3\x2\x2\x2\xC5\x7F\x3\x2\x2\x2\xC5\x82\x3\x2\x2"+
		"\x2\xC5\x85\x3\x2\x2\x2\xC5\x88\x3\x2\x2\x2\xC5\x8B\x3\x2\x2\x2\xC5\x8E"+
		"\x3\x2\x2\x2\xC5\x91\x3\x2\x2\x2\xC5\x94\x3\x2\x2\x2\xC5\x97\x3\x2\x2"+
		"\x2\xC5\x9A\x3\x2\x2\x2\xC5\x9D\x3\x2\x2\x2\xC5\xA0\x3\x2\x2\x2\xC5\xA3"+
		"\x3\x2\x2\x2\xC5\xA6\x3\x2\x2\x2\xC5\xA9\x3\x2\x2\x2\xC5\xAC\x3\x2\x2"+
		"\x2\xC5\xAF\x3\x2\x2\x2\xC5\xB2\x3\x2\x2\x2\xC5\xB5\x3\x2\x2\x2\xC5\xB8"+
		"\x3\x2\x2\x2\xC5\xBB\x3\x2\x2\x2\xC5\xBE\x3\x2\x2\x2\xC5\xC0\x3\x2\x2"+
		"\x2\xC5\xC3\x3\x2\x2\x2\xC6\xC9\x3\x2\x2\x2\xC7\xC5\x3\x2\x2\x2\xC7\xC8"+
		"\x3\x2\x2\x2\xC8\v\x3\x2\x2\x2\xC9\xC7\x3\x2\x2\x2\xCA\xCB\a+\x2\x2\xCB"+
		"\r\x3\x2\x2\x2\xCC\xCE\a+\x2\x2\xCD\xCC\x3\x2\x2\x2\xCD\xCE\x3\x2\x2\x2"+
		"\xCE\xCF\x3\x2\x2\x2\xCF\xD0\a,\x2\x2\xD0\xF\x3\x2\x2\x2\xD1\xD2\a\a\x2"+
		"\x2\xD2\xD3\x5\x10\t\x2\xD3\xD4\a\b\x2\x2\xD4\xD6\x3\x2\x2\x2\xD5\xD1"+
		"\x3\x2\x2\x2\xD6\xD9\x3\x2\x2\x2\xD7\xD5\x3\x2\x2\x2\xD7\xD8\x3\x2\x2"+
		"\x2\xD8\xDA\x3\x2\x2\x2\xD9\xD7\x3\x2\x2\x2\xDA\xE0\a+\x2\x2\xDB\xDD\a"+
		"/\x2\x2\xDC\xDE\x5\x12\n\x2\xDD\xDC\x3\x2\x2\x2\xDD\xDE\x3\x2\x2\x2\xDE"+
		"\xDF\x3\x2\x2\x2\xDF\xE1\a\x30\x2\x2\xE0\xDB\x3\x2\x2\x2\xE0\xE1\x3\x2"+
		"\x2\x2\xE1\x123\x3\x2\x2\x2\xE2\xE3\a\a\x2\x2\xE3\xE4\x5\x10\t\x2\xE4"+
		"\xE5\a\b\x2\x2\xE5\xE7\x3\x2\x2\x2\xE6\xE2\x3\x2\x2\x2\xE7\xEA\x3\x2\x2"+
		"\x2\xE8\xE6\x3\x2\x2\x2\xE8\xE9\x3\x2\x2\x2\xE9\xEB\x3\x2\x2\x2\xEA\xE8"+
		"\x3\x2\x2\x2\xEB\xEC\a+\x2\x2\xEC\xF2\a\n\x2\x2\xED\xEF\a/\x2\x2\xEE\xF0"+
		"\x5\x12\n\x2\xEF\xEE\x3\x2\x2\x2\xEF\xF0\x3\x2\x2\x2\xF0\xF1\x3\x2\x2"+
		"\x2\xF1\xF3\a\x30\x2\x2\xF2\xED\x3\x2\x2\x2\xF2\xF3\x3\x2\x2\x2\xF3\x123"+
		"\x3\x2\x2\x2\xF4\xF5\a\a\x2\x2\xF5\xF6\x5\x10\t\x2\xF6\xF7\a\b\x2\x2\xF7"+
		"\xF9\x3\x2\x2\x2\xF8\xF4\x3\x2\x2\x2\xF9\xFC\x3\x2\x2\x2\xFA\xF8\x3\x2"+
		"\x2\x2\xFA\xFB\x3\x2\x2\x2\xFB\xFD\x3\x2\x2\x2\xFC\xFA\x3\x2\x2\x2\xFD"+
		"\xFE\a+\x2\x2\xFE\x100\a\x31\x2\x2\xFF\x101\x5\x12\n\x2\x100\xFF\x3\x2"+
		"\x2\x2\x100\x101\x3\x2\x2\x2\x101\x102\x3\x2\x2\x2\x102\x123\a\x32\x2"+
		"\x2\x103\x104\a\a\x2\x2\x104\x105\x5\x10\t\x2\x105\x106\a\b\x2\x2\x106"+
		"\x108\x3\x2\x2\x2\x107\x103\x3\x2\x2\x2\x108\x10B\x3\x2\x2\x2\x109\x107"+
		"\x3\x2\x2\x2\x109\x10A\x3\x2\x2\x2\x10A\x10C\x3\x2\x2\x2\x10B\x109\x3"+
		"\x2\x2\x2\x10C\x10D\a+\x2\x2\x10D\x10E\a\t\x2\x2\x10E\x110\a/\x2\x2\x10F"+
		"\x111\x5\x12\n\x2\x110\x10F\x3\x2\x2\x2\x110\x111\x3\x2\x2\x2\x111\x112"+
		"\x3\x2\x2\x2\x112\x123\a\x30\x2\x2\x113\x114\a\a\x2\x2\x114\x115\x5\x10"+
		"\t\x2\x115\x116\a\b\x2\x2\x116\x118\x3\x2\x2\x2\x117\x113\x3\x2\x2\x2"+
		"\x118\x11B\x3\x2\x2\x2\x119\x117\x3\x2\x2\x2\x119\x11A\x3\x2\x2\x2\x11A"+
		"\x11C\x3\x2\x2\x2\x11B\x119\x3\x2\x2\x2\x11C\x11D\a+\x2\x2\x11D\x11F\a"+
		"\a\x2\x2\x11E\x120\x5\x12\n\x2\x11F\x11E\x3\x2\x2\x2\x11F\x120\x3\x2\x2"+
		"\x2\x120\x121\x3\x2\x2\x2\x121\x123\a\b\x2\x2\x122\xD7\x3\x2\x2\x2\x122"+
		"\xE8\x3\x2\x2\x2\x122\xFA\x3\x2\x2\x2\x122\x109\x3\x2\x2\x2\x122\x119"+
		"\x3\x2\x2\x2\x123\x11\x3\x2\x2\x2\x124\x129\x5\n\x6\x2\x125\x126\a\x6"+
		"\x2\x2\x126\x128\x5\n\x6\x2\x127\x125\x3\x2\x2\x2\x128\x12B\x3\x2\x2\x2"+
		"\x129\x127\x3\x2\x2\x2\x129\x12A\x3\x2\x2\x2\x12A\x13\x3\x2\x2\x2\x12B"+
		"\x129\x3\x2\x2\x2\x12C\x12E\a#\x2\x2\x12D\x12C\x3\x2\x2\x2\x12D\x12E\x3"+
		"\x2\x2\x2\x12E\x12F\x3\x2\x2\x2\x12F\x130\x5\n\x6\x2\x130\x131\a\x1A\x2"+
		"\x2\x131\x132\x5\n\x6\x2\x132\x15\x3\x2\x2\x2\x1D\x19\x1E\".JNT\x66h\xC5"+
		"\xC7\xCD\xD7\xDD\xE0\xE8\xEF\xF2\xFA\x100\x109\x110\x119\x11F\x122\x129"+
		"\x12D";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
